server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    session:
      timeout: 10

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/code_diary?serverTimezone=GMT%2B8&allowMultiQueries=true&characterEncoding=utf-8
    username: root
    password: 333
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true
